"""
prompt package
--------------
Contém todos os prompts do sistema organizados em prompts.py.
"""

from prompt.prompts import (
    PROMPT_ESPECIALISTA_RECOMENDACAO,
    PROMPT_ESPECIALISTA_SUPORTE,
    PROMPT_ESPECIALISTA_VENDAS,
    PROMPT_GUARDRAIL_INPUT,
    PROMPT_GUARDRAIL_OUTPUT,
    PROMPT_ORQUESTRADOR,
    PROMPT_ROUTER,
    RESPOSTA_BLOQUEIO,
)

__all__ = [
    "PROMPT_GUARDRAIL_INPUT",
    "PROMPT_GUARDRAIL_OUTPUT",
    "PROMPT_ROUTER",
    "PROMPT_ORQUESTRADOR",
    "PROMPT_ESPECIALISTA_RECOMENDACAO",
    "PROMPT_ESPECIALISTA_SUPORTE",
    "PROMPT_ESPECIALISTA_VENDAS",
    "RESPOSTA_BLOQUEIO",
]
